### ISSUE TITLE
Emitting on activity start

### ISSUE THREAD

**Issue by HaydenReeve** [serilog-tracing/serilog-tracing#130]
Hello 👋

After some significant use of SerilogTracings, I have found that I keep falling into the following pattern when debugging long-running sequential activities.

```C#
using (LoggerActivity _ = logger.StartActivity("Do the thing"))
{
    logger.Information("Do the thing");
    // Do the thing
}
```

Which then gives me the desired

```log
Do the thing
Do the thing completed in (2)ms
```

Ideally we could just use

```C#
using (LoggerActivity _ = logger.StartActivity("Do the thing"))
{
    // Do the thing
}
```

And get the desired output.

Would it be reasonable to suggest that we could investigate making this default functionality? Emitting on start and completion would assist with some sequential debugging and make the tracings library significantly more well-rounded.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! I've used a similar approach in the past, but I think it's too opinionated to be implemented in the base library. Creating an extension method on `ILogger` to do this is the way to do this for now.

**Comment by HaydenReeve** [comment]
Since the original post, I have been considering this further, and I agree that making it the default functionality is quite an opinionated approach.

But I also thought of an alternative which, if it's interesting for the folks here, might be worth considering;

If there was an implementation on LoggerActivity which spits out an early emit without the span and returns a LoggerActivity via a fluent interface, you could achieve something like this:

```C#
using (LoggerActivity _ = logger.StartActivity("Do the thing").Announce()
{
    // Do the thing
}
```

And get

```log
Do the thing
Do the thing completed in (5)ms
```

I'm not exactly sure about the terminology yet, but I would be happy to give it a go. It looks plausible to me from my initial tinkerings.

**Comment by nblumhardt** [comment]
The API and terminology work well; the feature overall is still something I think might be too opinionated for the library at this point, though.

Here's a quick extension method version:

```csharp
static class LoggerActivityExtensions
{
    [MessageTemplateFormatMethod(nameof(messageTemplate))]
    public static LoggerActivity AnnounceActivity(this ILogger logger, string messageTemplate, params object?[] args)
    {
        logger.Information(messageTemplate, args);
        return logger.StartActivity(messageTemplate, args);
    }
}
```

Writing it helps surface questions like: What level should the "announcement" be at? Should the activity still be announced even when the span is suppressed via sampling? Would it be nicer to include some indication in the announcement event that it's related to an activity (such as with the text `" starting"`? (The last one important because the `" completed in x"` text is only added in text outputs, leaving the two events with identical messages in other sinks.)

All are pretty straightforward to tweak via the extension method implementation, but would need either baked-in opinions or configuration if we made this a base library feature.
