### ISSUE TITLE
Seq says "The trace does not contain any spans" but a search returns matching SpanIds

### ISSUE THREAD

**Issue by Kesmy** [serilog-tracing/serilog-tracing#158]
On Seq 2024.3.12680

If I "Show" a Trace, Seq often reports "The trace does not contain any spans." If I "Find this Span," however, I get multiple results matching both the trace and span. I may be fundamentally misunderstanding something here, as I'm completely new to this tracing, but shouldn't those results be displayed in the Trace pane?

**Comment by nblumhardt** [comment]
Hi!

It's likely that the events you're finding with matching trace and span ids are log events, rather than spans.

You can tell spans from traces because spans have a little rectangular "timing" bar off to the right that shows the span's duration. You can see some examples of theses in the README.

Does this help?

**Comment by Kesmy** [comment]
That makes sense, thanks for the clarification.

I have some services which generate them on ASP.NET Core, but it appears there's no "good" automatic way to get that same generation on an ASP.NET 4.x webapp. It feels like I might be inventing another wheel here, but the OpenTelemetry SDK's logging leaves a bit to be desired. If you've any suggestions, I'd love to hear them, but I'll close this since my question was answered.

**Comment by nblumhardt** [comment]
Thanks for the follow-up! https://github.com/serilog-tracing/serilog-tracing/issues/145 has some discussion of how to add tracing to classic ASP.NET with SerilogTracing, HTH!
