### ISSUE TITLE
Cannot instrument activities

### ISSUE THREAD

**Issue by srogovtsev** [serilog-tracing/serilog-tracing#34]
The usual pattern for emitting custom activities in OpenTelemetry goes [along these lines](https://opentelemetry.io/docs/languages/net/instrumentation/):

```cs
const string SourceName = "MyApplication.MySource";

//this is to be accessible in the application
var source = new ActivitySource(SourceName);

//this is somewhere in the OpenTelemetry configuration
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource(SourceName) //<--this is where we bind one to another
    .Build();

//somewhere in the code which we instrument
var rootActivity = source.StartActivity();
```

The important thing here is that OpenTelemetry works via `System.Diagnostics.ActivityListener`, which is then passed to `System.Diagnostics.ActivitySource.AddActivityListener` and filters activities by name (see https://github.com/open-telemetry/opentelemetry-dotnet/blob/dfd27c50408e770963f9d60880c1da04810c409d/src/OpenTelemetry/Trace/TracerProviderSdk.cs#L107-L283).

I would expect _SerilogTracing_ to support the same model in `TracingConfiguration.Instrument.With`, but unexpectedly it deals in `DiagnosticListener`, not `ActivityListener` (the interface name `IActivityInstrumentor` adds to the confusion here). I believe this might prove an obstacle for adoption, as it doesn't allow for easy interoperation.

I kinda understand where this confusion comes from, because both `HttpClient` and `AspNetCore` emit information from both `ActivitySource` and `DiagnosticSource` as well, and the flow is... complex, let's say (https://github.com/open-telemetry/opentelemetry-dotnet/blob/dfd27c50408e770963f9d60880c1da04810c409d/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs#L84-L88).

I would say that as the adoption for OpenTelemetry grows, there'll be more and more `Activity`-based tracing in the new code, so this model is worth supporting. I can try drafting a basic example, if you're interested.

**Comment by nblumhardt** [comment]
Hi @srogovtsev, thanks for the feedback.

The naming around `Instrument.With` might be off; it's currently intended to provide that bridge between diagnostic sources and activities.

SerilogTracing does see and bind to activity sources, but there isn't currently an API in SerilogTracing for participating in the `Activity` &rarr; `LogEvent` mapping, or for adding additional context to `Activity` instances, which it sounds like you are looking for.

An example scenario would be great, if you can pass one on :+1:

**Comment by nblumhardt** [comment]
Hi again! Just taking another look at this, and trying to pinpoint the gap...

When a custom activity is created in SerilogTracing, all of the "instrumentation" is normally inline, e.g.:

```csharp
// JobId property exposed through `System.Diagnostics.Activity.Tags`:
using var activity = _log.StartActivity("Process job {JobId}", 5);

// Also added to `Activity.Tags`
activity.AddProperty("ItemType", "beans");

// Exception is added to `Activity.Events` and status is `Activity.Status`:
activity.Complete(LogEventLevel.Error, exception);
```

I think this is counter to the idea of activities being created with opaque/symbolic names, and the data being attached elsewhere through enrichment. It seems on the surface that the indirect approach would work well for optional instrumentation in framework components and libraries, but in application code, the direct approach is much more compact and pleasant.

Definitely still open to making some improvements, just trying to get a handle on the scenario :-) Thanks!

**Comment by srogovtsev** [comment]
I”ll try to build a runnable example tomorrow (my time, we’re unfortunately on almost opposite sides of the globe).

**Comment by srogovtsev** [comment]
Okay, here we go: https://github.com/srogovtsev/serilog-tracing/tree/feature/activity-instrumentation/example/ActivityTracing

Let's pretend [this](https://github.com/srogovtsev/serilog-tracing/blob/3ee2cb2a165cfb2748e2b2c7a3dd5c1d3aa52ab0/example/ActivityTracing/Library/Worker.cs#L3-L21) is our "library" code: 
```cs
internal class Worker(ILogger<Worker> logger)
{
    //usually this would be separate, but let's pretend
    public const string ActivitySourceName = "MyLibrary";
    private static readonly ActivitySource ActivitySource = new(ActivitySourceName);

    private readonly Guid _id = Guid.NewGuid();
    public void Run()
    {
        // ReSharper disable once ExplicitCallerInfoArgument
        using var activity = ActivitySource.StartActivity(name: "Worker Run", kind: ActivityKind.Internal, tags: new Dictionary<string, object?>
        {
            {"WorkerId", _id}
        });
        logger.LogInformation("Worker {WorkerId} was run", _id);
    }
}
```

It uses only generic dependencies - `System.Diagnostics` (for `ActivitySource`) and `Microsoft.Extensions.Logging` for, well, logging.

[Its consumer](https://github.com/srogovtsev/serilog-tracing/blob/aa0b42cef970f3aafa4d06f2a10415c71ff3d4ac/example/ActivityTracing/Program.cs), on the other hand, is very specific:

```cs
const string programSourceName = "Program";

using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource(programSourceName)
    .AddSource(Worker.ActivitySourceName)
    .AddOtlpExporter()
    .Build();

using var logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateLogger();

using var loggerFactory = LoggerFactory
    .Create(builder => builder.AddSerilog(logger));

//end of configuration, let's go

using var source = new ActivitySource(programSourceName);

using var root = source.StartActivity();

logger.Information("Started");

new Worker(loggerFactory.CreateLogger<Worker>()).Run();
new Worker(loggerFactory.CreateLogger<Worker>()).Run();

logger.Information("Finished");
```

It uses OpenTelemetry for tracing and Serilog for logging. Pay attention to the `AddSource(Worker.ActivitySourceName)` line, which is the only thing that binds the library to our tracing.

Lo and behold, everything works as expected (and we even have our worker ids in Zipkin):

```
[14:45:40 INF] Started
[14:45:40 INF] Worker 9c7fc289-2847-4ff6-a6d2-ab793639b4b1 was run
[14:45:40 INF] Worker 632fc706-838b-4131-8af5-0183152e5554 was run
[14:45:40 INF] Finished
```

![image](https://github.com/serilog-tracing/serilog-tracing/assets/2332517/4cf7ae51-c86b-43e4-a70a-e1d581a63082)


Now then, [we add _SerilogTracing_](example/ActivityTracing/Program.cs) (I should have replaced the OpenTelemetry completely, but I don't want to do so, as I want to show its output):

```cs
using var _ = new TracingConfiguration().EnableTracing();
using var source = new ActivitySource(programSourceName);
using var root = source.StartActivity();
using var serilog = logger.StartActivity("Serilog root");
logger.Information("Started");
new Worker(loggerFactory.CreateLogger<Worker>()).Run();
```

Configuration part is omitted, but I've added `StartActivity` from the _SerilogTracing_.

Here's what Zipkin (**via OpenTelemetry**) shows:
![image](https://github.com/serilog-tracing/serilog-tracing/assets/2332517/76ba4fac-2c3c-4855-8d0c-75cfd5083791)
And this is exactly what I expect, because I had my original instrumentation, and I've added one more activity from Serilog in the middle of it.

But here's what sees _Serilog_:

```
[14:48:40 INF] │ Started
[14:48:40 INF] │ Worker e037253e-deda-44a4-891f-3d1ee559e21f was run
[14:48:40 INF] │ Worker 6a98555f-a3b6-47b7-b1ca-1a2a7e7066bc was run
[14:48:40 INF] │ Finished
[19:48:40 INF] ├ Serilog root (126.766 ms)
```

Its own activities are there, but mine aren't.

And this is where my issues comes from: how do I make _SerilogTracing_ honor the same instrumentation that I'm already using with OpenTelemetry?

**Comment by nblumhardt** [comment]
Ah, I see! Thanks for taking the time to produce a repro @srogovtsev, much appreciated.

This is the same footgun that got me in a demo to a room of conference attendees a month ago ---- it's still hurting 😅.

You're not using the static `Log.Logger` property, so you need to tell `EnableTracing()` where to write those spans:

```csharp
using var _ = new TracingConfiguration()
    .Instrument.WithDefaultInstrumentation(false)
    .EnableTracing(logger);
```

With that change everything looks much nicer:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/342712/70ab9347-0767-4235-a441-f824f7a6884c)

We have #36 open to attempt to make this more discoverable. I might add a "Troubleshooting" section to the README to cover this, too, however that feature comes out...

**Comment by srogovtsev** [comment]
I really hate it when it's this obvious. Thanks for pointing it out.

But then there's another question: so, unlike OpenTelemetry, it instruments everything by default? That'd be _lots_ of data in some systems.

**Comment by nblumhardt** [comment]
The `Instrument` configuration is the bridge from diagnostic sources to activities, so the `WithDefaultInstrumentation()` call here is just turning off the default `HttpClient` request descriptions (you'll get something similar via OTel, which will be more in line with what you want in your scenario).

But - trace sources are controlled using `MinimumLevel` in SerilogTracing. It will show you all possible traces in your application by default, and you need to switch them off the same way that you switch off logging:

```csharp
    .MinimumLevel.Override("Npgsql", LevelAlias.Off)
```

That still might not be ideal if you're intending to produce very fine-grained traces (emulating execution profiles) and coarse-grained logs; some additional options in `TracingConfiguration` may help with that down the track. Right now the default experience is aiming for out-of-the box discoverability, and to encourage fairly coarse-grained, application-oriented spans.

**Comment by srogovtsev** [comment]
> But - trace sources are controlled using MinimumLevel in SerilogTracing. 

I suspected this much, and I'm not sure this is very easy to use when one has a lot of activity sources which they don't control. OpenTelemetry offers opt-_in_, your model is more opt-_out_. While I understand your desire for pit-of-success kind of defaults, I'd appreciate an optional configuration like this:

```cs
new TracingConfiguration()
.Instrument.Activities(activityOptions => {
  activityOptions.IncludeAll = true; //<--default
  //or
  activityOptions.IncludeAll = false;
  activityOptions.AddSource("some")
})
```

This was I can easily switch from OpenTelemetry to SerilogTracing with roughly same semantics.

> Right now the default experience is aiming [...] to encourage fairly coarse-grained, application-oriented spans.

The problem is that we don't control the spans emitted by the _libraries_ we consume, and as OpenTelemetry gets more and more traction in .net world, there'll be more and more `Activities` floating around. [The guidance](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing#getting-started-for-net-library-developers) is already leaning in that direction.

**Comment by srogovtsev** [comment]
...actually, this discussion led me to a weird idea of my own, which might need some of the code from your implementation. I'll try to do a PoC ASAP so that you would be able to consider opening some internals _if_ that would be needed.

**Comment by nblumhardt** [comment]
The PoC is interesting, could definitely be a nice alternative for what you're aiming to do.

I am not sure how much of `ActivityInstrumentation` we'll end up wanting to expose at this point - it's likely that the `Get*` and `TryGet*` methods there will be closed, and also likely it will shift from being a static class, to being an argument passed in the `IActivityInstrumentor.InstrumentActivity()` method. Just mentioning this as a heads-up.

Since the activities reaching your exporter are unlikely to have `LoggerActivity` instances attached (since they'll be coming from library components not using SerilogTracing) this might not matter too much to you.

I've raised a ticket for opting into activity sources. I might close this one now, as it's grown into rather a long and broad thread, but feel free to tack any more thoughts on here, or open a new one if there's more you think we can improve.

**Comment by ngbrown** [comment]
I'm trying to add activity templates to a library that is only implementing `ActivitySource` and not `DiagnosticListener`. Like this issue mentions, `IActivityInstrumentor` requires `DiagnosticListener` to be used by the library providing the instrumentation.

This issue is marked as closed, but I don't see the solution. Was there a pull request or follow up issue to be able to customize a `ActivityListener` instead of `DiagnosticListener` like `IActivityInstrumentor`  does?

**Comment by nblumhardt** [comment]
Hi @ngbrown ! What you're trying to do is one of the core use cases of SerilogTracing, so it should work straight out of the box with no config. Level overrides in your Serilog configuration are one common culprit to check, since these can end up suppressing spans just like they would suppress log events.

If this doesn't narrow it down, could you please add a few more details into a new ticket, e.g. what your Serilog and SerilogTracing configuration looks like, the kind of activity you're expecting to see, and the output you're getting, if any? Pretty confident we'll be able to spot the problem :+1:.

**Comment by ngbrown** [comment]
Hi @nblumhardt  I'm talking about setting a custom template on an activity/trace being logged to Seq, not about the severity level of the trace. Much like is done in the implementations of `IActivityInstrumentor` here: https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing.Instrumentation.AspNetCore/Instrumentation/AspNetCore/HttpRequestInActivityInstrumentationOptions.cs#L25-L26

I am trying to integrate with the new `ActivitySource` instrumentation available in v7 of RabbitMQ.Client (now at ver 7.0.0-rc.11).

This matters because the default trace log text does not show in Seq as following a template, so every different queue or channel received from or sent on results in a different message type:

![Screenshot 2024-10-03 220346](https://github.com/user-attachments/assets/d5c0096a-eb6f-4e1f-8dcb-62d0765ead41)

I initially went down the path of trying to implement something similar to what was done for `SerilogTracing.Instrumentation.SqlClient`, but came to the realization that the RabbitMQ.Client isn't using `DiagnosticListener`/`DiagnosticSource` at all, so `IActivityInstrumentor.ShouldSubscribeTo` is never called using a RabbitMQ related `diagnosticListenerName`. This led me to this issue, because it does talk about libraries that only use `ActivitySource` and not `DiagnosticListener`.

This does seems to be following the guidance from the .NET team because their 2020 design decision says they are simplifying the recommended pattern of activity objects to [not use `DiagnosticSource`](https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/activity-improvements.md#:~:text=We%20are%20simplifying%20the%20pattern%20to%20something%20like%3A). 

I can inject my own message template overrides for SerilogTracing if I setup my own `ActivityListener`, but this relies on the ordering of calls to subscribers, so doesn't seem like a great idea.

<details>
<summary>Expand for Program.cs. See AddAmqpActivityInterceptor() for hacky way to inject custom templates and assign parameters to Activities about to be sent to Seq.</summary>

```cs
using System.Diagnostics;
using GrpcGreeter.Services;
using Serilog;
using Serilog.Events;
using Serilog.Parsing;
using Serilog.Templates.Themes;
using SerilogTracing;
using SerilogTracing.Expressions;
using SerilogTracing.Instrumentation;

namespace GrpcGreeter;

public class Program
{
    // Works in the console, but Seq (as of 2024.3.12250) doesn't yet seem to support this
    const bool UseDottedPropertyNames = false;

    public static void Main(string[] args)
    {
        AppContext.SetSwitch("Serilog.Parsing.MessageTemplateParser.AcceptDottedPropertyNames", UseDottedPropertyNames);

        Log.Logger = new LoggerConfiguration()
            .Enrich.WithProperty("Application", typeof(Program).Assembly.GetName().Name)
            .WriteTo.Console(Formatters.CreateConsoleTextFormatter(TemplateTheme.Code))
            .WriteTo.Seq("http://localhost:5341")
            .CreateLogger();

        try
        {
            var builder = WebApplication.CreateBuilder(args);

            // Additional configuration is required to successfully run gRPC on macOS.
            // For instructions on how to configure Kestrel and gRPC clients on macOS, visit https://go.microsoft.com/fwlink/?linkid=2099682

            AddAmqpActivityInterceptor();

            // Add services to the container.
            builder.Services.AddSerilog();
            builder.Services.AddSingleton(
                new ActivityListenerConfiguration()
                    .Instrument.AspNetCoreRequests()
                    .Instrument.RabbitMQClient()
                    .TraceToSharedLogger());
            builder.Services.AddGrpc();

            builder.Services.AddSingleton<FibService>();
            builder.Services.AddHostedService<RabbitMqServer>();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            app.MapGrpcService<GreeterService>();
            app.MapGet("/",
                () =>
                    "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

            app.Run();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Application terminated unexpectedly");
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    private static void AddAmqpActivityInterceptor()
    {
        var messageTemplateSubscriber =
            new MessageTemplateParser().Parse(UseDottedPropertyNames
                ? "AMQP {messaging.operation} {messaging.rabbitmq.destination.routing_key}"
                : "AMQP {Operation} {RoutingKey}");
        var messageTemplatePublisher =
            new MessageTemplateParser().Parse(UseDottedPropertyNames
                ? "AMQP {messaging.operation} {messaging.destination.name}"
                : "AMQP {Operation} {DestinationName}");

        var activityListener = new ActivityListener
        {
            ShouldListenTo = source =>
                source.Name == "RabbitMQ.Client.Subscriber" ||
                source.Name == "RabbitMQ.Client.Publisher",
            ActivityStopped = OnActivityStopped
        };
        ActivitySource.AddActivityListener(activityListener);
        return;

        void OnActivityStopped(Activity activity)
        {
            if (activity.Source.Name == "RabbitMQ.Client.Subscriber")
            {
                ActivityInstrumentation.SetMessageTemplateOverride(activity, messageTemplateSubscriber);
                foreach (var (k, v) in activity.Tags)
                {
                    switch (k)
                    {
                        case "messaging.operation":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "Operation",
                                new ScalarValue(v));
                            break;
                        case "messaging.rabbitmq.destination.routing_key":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "RoutingKey",
                                new ScalarValue(v));
                            break;
                    }
                }
            }
            else if (activity.Source.Name == "RabbitMQ.Client.Publisher")
            {
                ActivityInstrumentation.SetMessageTemplateOverride(activity, messageTemplatePublisher);
                foreach (var (k, v) in activity.Tags)
                {
                    switch (k)
                    {
                        case "messaging.operation":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "Operation",
                                new ScalarValue(v));
                            break;
                        case "messaging.destination.name":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "DestinationName",
                                new ScalarValue(v));
                            break;
                    }
                }
            }
        }
    }
}
```
</details>

So now Seq shows a templated trace:

![Screenshot 2024-10-03 222317](https://github.com/user-attachments/assets/998cf56b-868b-43e9-b87e-9aa4417fe63b)

But because Seq doesn't seem to support `AcceptDottedPropertyNames` property yet, I end up with duplicate properties to support the templating in Seq:

![Screenshot 2024-10-03 222454](https://github.com/user-attachments/assets/b2d9b1fd-82e1-4a21-ba95-1bb4f92c19a9)

So what I'm asking for is a way to do set a custom template and properties on a to-be logged trace somewhere around https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing/Interop/LoggerActivityListener.cs#L115-L119 or within [`ActivityConvert`](https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing/Interop/ActivityConvert.cs#L25).

My test project is available on the `rabbit-rpc` branch here: https://github.com/ngbrown/grpc-testing/commits/rabbit-rpc/

**Comment by nblumhardt** [comment]
Thanks @ngbrown, I think I understand now 👍

Some kind of instrumentation hook to customize external activities like this would be nice. Is it possible to move your comment to a new issue? We can follow up and figure out what a design would look like, there. Thanks!
