### ISSUE TITLE
Support configuring an initial `LogEventLevel` for externally created activities

### ISSUE THREAD

**Issue by KodrAus** [serilog-tracing/serilog-tracing#55]
This is part of a solution to #31, but also somewhat distinct.

## Summary

When creating activities through `ILogger.StartActivity()` you get to specify an initial `LogEventLevel` that determines what level the activity will be assigned when converted into a `LogEvent` on completion. This level is also used to avoid creating activities below the minimum level of the target `ILogger`. The `LogEventLevel` needs to be supplied because activities don't have levels in the traditional sense like `Debug`, `Information`, or `Fatal`. They instead have a status of `Unset`, `Ok`, or `Error`. When activities are created outside of SerilogTracing, such as in `HttpClient`, they don't get a chance to specify a level. This proposal is for a mechanism to map `Activity.OperationName` to a `LogEventLevel` for these externally created activities. This gives them a way to participate in level-based filtering, just like `ILogger.StartActivity()` does.

## Filtering spans is different from filtering logs

Spans (activities) have an important difference from logs when it comes to filtering; they're not independent. If a child span is emitted, then its parent must be also. When this doesn't happen you end up with orphan spans. These degrade the usefulness of the resulting trace because you can't distinguish a missing span from one that completed but was filtered out, or one that started but never completed, perhaps due to some kind of deadlock. It also breaks the hierarchy of the trace; all orphan spans would need to appear as root spans, even when this isn't actually the case.

## Plug level-based filtering into our `ActivitySource.Sample`

If an activity is created, it must be emitted to avoid orphan spans. That means any filtering on activities needs to be done at the point of creation. In `ILogger.StartActivity()` we already do this by using the initial `LogEventLevel`. For externally created activities, this is currently done on completion. In this proposal, externally created activities will instead use the mapping from `Activity.OperationName` to `LogEventLevel` in our `ActivitySource.Sample` function to inform external code of SerilogTracing's interest in a particular activity. This brings externally created activities in-line with those created through `ILogger.StartActivity`. It also gives you a nice way to adjust the levels of activities created by different components in a way that's already familiar to Serilog users.

Note that if another `ActivitySource` may show more interest in a given activity than SerilogTracing does then we should still emit it by default, even if it's below the minimum level specified. This may be surprising to some users though, so we should allow you to opt-out of it, at the risk of producing orphan spans.

**Comment by nblumhardt** [comment]
@KodrAus I've tried summarizing this simply for the README as:

---

## Levelling for external activity sources

SerilogTracing can consume activities from .NET itself, and libraries that don't themselves use SerilogTracing. By default, you'll see spans for all activities, from all sources, in your Serilog output.

To "turn down" the level of tracing performed by an external activity source, use SerilogTracing's `InitialLevel` configuration to set a level for spans from that source:

```csharp
    .InitialLevel.Override("Npgsql", LogEventLevel.Debug)
```

In this example, when activities from the [Npgsql](https://github.com/npgsql/npgsql) activity source are assigned an initial level of `Debug`, they'll be suppressed unless your Serilog logger has debug logging enabled.

### Why is this an _initial_ level?

The initial level assigned to a source determines whether activities are created by the source. When the activity is completed, it may be recorded at a higher level; for example, a span created at an initial `Information` level may complete as an `Error` (but not at a lower level such as `Debug`, because doing so may suppress the span cause the trace hierarchy to become incoherent).

---

What do you think?
