### ISSUE TITLE
Do we have an example using asp.net?

### ISSUE THREAD

**Issue by aqbjteddy** [serilog-tracing/serilog-tracing#99]
Hi,

This library is fantastic, I just cloned the repository and found the example project only supports asp.net core.

Do we have an example project using asp.net? 

Thanks!

**Comment by nblumhardt** [comment]
Hi! Thanks for dropping by.

It's been a very, very long time since I worked with ASP.NET so I could be completely off-base here, but I think you should be able to use the same techniques that _SerilogWeb.Classic_ uses to hook into the request lifecycle, start an activity when the request begins, and complete it when the request ends:

https://github.com/serilog-web/classic

I'd love to hear if you're able to figure this out/get something working. Good luck with it!

**Comment by aqbjteddy** [comment]
@nblumhardt Thanks for the reply. I will look into that project.
